---
- name: Install wireguard
  package: name=wireguard-tools
- name: Enable ip forwarding
  copy:
    content: "net.ipv4.ip_forward = 1\nnet.ipv6.conf.all.forwarding = 1"
    dest: /etc/sysctl.d/99-ipforward.conf
  notify: Enable ip forwarding

- name: WireGuard configurations
  template:
    src: wireguard.conf.j2
    dest: /etc/wireguard/{{ item.name }}.conf
    owner: root
    group: root
    mode: 0600
  with_items: "{{ wireguard_configs }}"
  register: wireguard_config_res

- name: Enable WireGuard configurations
  service: name=wg-quick@{{ item.name }} state=started enabled=True
  with_items: "{{ wireguard_configs }}"

- name: Restart WireGuard on config change
  service: name=wg-quick@{{ item.item.name }} state=restarted
  when: item.changed
  with_items: "{{ wireguard_config_res.results }}"

- name: Create service configuration directoryies
  file:
    state: directory
    path: /etc/systemd/system/wg-quick@{{ item.name }}.service.d/
    mode: 0755
  with_items: "{{ wireguard_configs }}"
  tags: wireguard_service_config
- name: Configure services to start after wireguard
  template:
    src: before-services.conf.j2
    dest: /etc/systemd/system/wg-quick@{{ item.name }}.service.d/before-service.conf
  with_items: "{{ wireguard_configs }}"
  tags: wireguard_service_config
