---
- include_vars: "{{ item }}"
  with_first_found:
    - "../vars/{{ ansible_os_family }}.yml"
    - "../vars/Default.yml"
  tags: php_extensions

- name: Install php packages
  package: name={{ item }}
  with_items: "{{ php_packages }}"

- name: Set php-fpm listen group to caddy
  lineinfile:
    path: '{{ php_ini_path }}/php-fpm.d/www.conf'
    regexp: '^listen.group ='
    line: 'listen.group = {{ caddy_user }}'
- name: Enable php extensions
  lineinfile:
    path: '{{ php_ini_path }}/php.ini'
    insertafter: '^;?extension='
    regexp: '^;?extension={{ item }}'
    line:   'extension={{ item }}'
  with_items: '{{ php_extensions | default([]) }}'
  notify: Reload php-fpm
  tags: php_extensions

- name: Configure php
  lineinfile:
    path: /etc/php/php.ini
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items: "{{ php_settings | default([]) }}"
  tags: php_settings
  notify: Reload php-fpm

- name: Enable php-fpm
  service: name=php-fpm state=started enabled=True
