---
- name: Install sshd
  package: name=openssh

- name: Add host vars
  set_fact:
    sshd_options: "{{ sshd_settings + sshd_host_settings }}"

- name: Configure sshd
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items: "{{ sshd_options }}"
  notify: Reload sshd

- name: Start and enable sshd
  service: name=sshd state=started enabled=True
